export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";


export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const ALL_NEWS_FAIL = 'ALL_NEWS_FAIL'
export const ALL_NEWS_SUCCESS = 'ALL_NEWS_SUCCESS'
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS'

export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'


export const ALL_CAUSE_FAIL = 'ALL_CAUSE_FAIL'
export const EDIT_CAUSE_SUCCESS = 'EDIT_CAUSE_SUCCESS'
export const ALL_CAUSE_SUCCESS = 'ALL_CAUSE_SUCCESS'


export const ALL_COMPAIGN_FAIL = 'ALL_COMPAIGN_FAIL'
export const ALL_COMPAIGN_SUCCESS = 'ALL_COMPAIGN_SUCCESS'
export const EDIT_COMPAIGN_SUCCESS = 'EDIT_COMPAIGN_SUCCESS'

export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'

export const ALL_DONATIONPRODUCT_FAIL = 'ALL_DONATIONPRODUCT_FAIL'
export const ALL_DONATIONPRODUCT_SUCCESS = 'ALL_DONATIONPRODUCT_SUCCESS'
export const EDIT_DONATIONPRODUCT_SUCCESS = 'EDIT_DONATIONPRODUCT_SUCCESS'


export const ALL_DONATIONREQUEST_FAIL = 'ALL_DONATIONREQUEST_FAIL'
export const ALL_DONATIONREQUEST_SUCCESS = 'ALL_DONATIONREQUEST_SUCCESS'
export const EDIT_DONATIONREQUEST_SUCCESS = 'EDIT_DONATIONREQUEST_SUCCESS'
